'use client'

import { useState } from 'react'

export default function PaymentHistoryTable() {
  const [isModalOpen, setIsModalOpen] = useState(false)

  const paymentHistory = [
    {
      date: '2025-06-01',
      referee: 'Jane Cooper',
      gameId: 'GAME-001',
      amount: '$45',
      status: 'Paid',
    },
    {
      date: '2025-06-03',
      referee: 'John Smith',
      gameId: 'GAME-002',
      amount: '$40',
      status: 'Paid',
    },
    {
      date: '2025-06-05',
      referee: 'Emily Johnson',
      gameId: 'GAME-003',
      amount: '$50',
      status: 'Pending',
    },
    {
      date: '2025-06-07',
      referee: 'Michael Lee',
      gameId: 'GAME-004',
      amount: '$55',
      status: 'Failed',
    },
    {
      date: '2025-06-09',
      referee: 'Sarah Kim',
      gameId: 'GAME-005',
      amount: '$60',
      status: 'Paid',
    },
    {
      date: '2025-06-10',
      referee: 'Tom Brown',
      gameId: 'GAME-006',
      amount: '$35',
      status: 'Pending',
    },
    {
      date: '2025-06-11',
      referee: 'Laura Wilson',
      gameId: 'GAME-007',
      amount: '$65',
      status: 'Paid',
    },
    {
      date: '2025-06-12',
      referee: 'Daniel Evans',
      gameId: 'GAME-008',
      amount: '$50',
      status: 'Paid',
    },
    {
      date: '2025-06-13',
      referee: 'Nancy Hall',
      gameId: 'GAME-009',
      amount: '$55',
      status: 'Failed',
    },
    {
      date: '2025-06-14',
      referee: 'Greg Adams',
      gameId: 'GAME-010',
      amount: '$70',
      status: 'Pending',
    },
  ]

  return (
    <div className="mt-8">
      <h2 className="text-lg font-semibold text-gray-900 mb-4">Payment History</h2>
      <div className="overflow-x-auto">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            <tr>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Date
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Referee
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Game ID
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Amount
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Payment Method
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Receipt
                <div className="text-[10px] text-gray-400 normal-case">Receipts generated by Stripe</div>
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Status
              </th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-200">
            {paymentHistory.slice(0, 5).map((payment, idx) => (
              <tr key={idx}>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{payment.date}</td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{payment.referee}</td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{payment.gameId}</td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{payment.amount}</td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">Visa **** 0000</td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-indigo-600 hover:underline cursor-pointer">Download</td>
                <td className="px-6 py-4 whitespace-nowrap text-sm">
                  <span
                    className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${
                      payment.status === 'Paid'
                        ? 'bg-green-100 text-green-800'
                        : payment.status === 'Pending'
                        ? 'bg-yellow-100 text-yellow-800'
                        : 'bg-red-100 text-red-800'
                    }`}
                  >
                    {payment.status}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <div className="mt-4 flex justify-end space-x-2">
        <button
          type="button"
          onClick={() => setIsModalOpen(true)}
          className="inline-flex items-center justify-center rounded-md border border-gray-300 bg-white px-3 py-1 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50"
        >
          Expand
        </button>
        <button
          type="button"
          onClick={() => alert('Export CSV (simulated)')}
          className="inline-flex items-center justify-center rounded-md border border-gray-300 bg-white px-3 py-1 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50"
        >
          Export CSV
        </button>
      </div>
      <p className="mt-1 text-xs text-gray-500 text-right">
        Last CSV Export: June 8, 2025, 10:15 AM
      </p>
      <p className="mt-1 text-xs text-gray-500 text-right">
        {`Showing ${Math.min(5, paymentHistory.length)} of ${paymentHistory.length} records`}
      </p>
      {isModalOpen && (
        <div className="fixed inset-0 z-50 bg-black bg-opacity-50 flex items-center justify-center px-4 py-8 sm:px-4">
          <div className="bg-white p-6 rounded shadow-lg w-full max-w-4xl max-h-[80vh] overflow-y-auto relative space-y-4">
            <button
              type="button"
              onClick={() => setIsModalOpen(false)}
              className="absolute top-2 right-2 text-gray-400 hover:text-gray-600"
            >
              ✕
            </button>
            <h2 className="text-lg font-semibold text-gray-900 mb-4">Full Payment History</h2>
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Referee</th>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Game ID</th>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Amount</th>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Payment Method</th>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Receipt
                      <div className="text-[10px] text-gray-400 normal-case">Receipts generated by Stripe</div>
                    </th>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {paymentHistory.map((payment, idx) => (
                    <tr key={idx}>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{payment.date}</td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{payment.referee}</td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{payment.gameId}</td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{payment.amount}</td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">Visa **** 0000</td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-indigo-600 hover:underline cursor-pointer">Download</td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm">
                        <span
                          className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${
                            payment.status === 'Paid'
                              ? 'bg-green-100 text-green-800'
                              : payment.status === 'Pending'
                              ? 'bg-yellow-100 text-yellow-800'
                              : 'bg-red-100 text-red-800'
                          }`}
                        >
                          {payment.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
